### PR TITLE
feat: show jobset & eval details, rewrite in rust

### PR DESCRIPTION
**Pull request by bryango**
**Summary:** show jobset & eval details, rewrite in rust, bump to v2. Note that:

- Obviously, you don't have to merge this at all :laughing: as the patch significantly complexifies the codebase, making it harder to maintain or review (though rust does make it easier to package the program and protects it against bit rot, compared to python).
- The rewrite in rust is _not_ justified, it's just a personal preference. As an amateur programmer, when I need some functionality (e.g. colored texts, aligned tables), I simply add a library :laughing: In rust I `cargo add` when necessary without much worrying (after checking the reputation of the depended crate, of course), while in python, I do not feel as comfortable to just pull in random dependencies.
- I am absolutely okay if the final decision is to not merge this! I just want to share it upstream as this extended v2 version has been serving me well.

## features

- Print recent evaluations of the jobset if no package is specified
Jobset status
- Add an `--eval` flag for information about a specific evaluation
Eval status
- Infer the current stable Nixpkgs release (e.g. `24.05`) with a hack
Stable channel
- Support standard channel names (e.g. `nixos-unstable`)
- Generate shell completions with `--shell-completion SHELL`
- Print nicely formatted, colored and aligned tables

### CODE REVIEW

**Comment by makefu** [comment]
Hey! At first whoa, thanks alot for your effort! I saw your PR 2 weeks ago but i was just a bit overwhelmed :) i will check out your rebuild and give back some feedback afterwards!

**Comment by makefu** [comment]
The Pull Request looks good and i would like to merge the PR under sole condition that you would have to become one of the maintainers of hydra-check with the power (and responsibility) to handle issues and merge requests together with me and @Artturin 

@Artturin i hope you are also fine with that :100:

**Comment by bryango** [comment]
> The Pull Request looks good and i would like to merge the PR under sole condition that you would have to become one of the maintainers of hydra-check with the power (and responsibility) to handle issues and merge requests together with me and Artturin

I am perfectly fine with that! It would be an honor! Thank you!

In the latest push I added two more commits: one is a rename of some internal objects (along with extra documentations) such that it would be clearer for future contributors, and the other is an improvement of the `--eval` cli processing such that one can simply do e.g. `hydra-check --eval rustc` for the latest eval filtered by `rustc`.

**Comment by makefu** [comment]
@bryango thanks a lot for your efforts! I've added you as a maintainer to the project.

**Comment by bryango** [comment]
Thank you very much! If there is any issue, feel free to ping me anytime!

**Pull request merged**
